import fs from 'node:fs';
import path from 'node:path';

const records = [
  {
    PublicRef: 'MRH-1001',
    Type: '2BHK',
    Sector: 'Sector 43',
    Rent: '55K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Featured',
    WebsiteDescription: '',
    'Property No': '810',
    'Room No': '103',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1002',
    Type: '1BHK',
    Sector: 'Sector 43',
    Rent: '35K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '874',
    'Room No': '301',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1003',
    Type: '1RK',
    Sector: 'Sector 52',
    Rent: '14K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Featured',
    WebsiteDescription: '',
    'Property No': '149',
    'Room No': '303',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1004',
    Type: '1RK',
    Sector: 'Sector 52',
    Rent: '14K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '149',
    'Room No': '103',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1005',
    Type: '1RK',
    Sector: 'Sector 52',
    Rent: '14K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '149',
    'Room No': '406',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1006',
    Type: '1BHK',
    Sector: 'Sector 52',
    Rent: '35K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Featured',
    WebsiteDescription: '',
    'Property No': '755',
    'Room No': '501',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1007',
    Type: '1BHK',
    Sector: 'Sector 52',
    Rent: '35K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '755',
    'Room No': '504',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1008',
    Type: '2BHK',
    Sector: 'Sector 43',
    Rent: '40K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '13',
    'Room No': '103',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1009',
    Type: '2BHK',
    Sector: 'Sector 43',
    Rent: '45K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Featured',
    WebsiteDescription: '',
    'Property No': 'EZ',
    'Room No': '102',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1010',
    Type: '1RK',
    Sector: 'Sector 43',
    Rent: '25K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '1301P',
    'Room No': 'G005',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1011',
    Type: '1BHK',
    Sector: 'Sector 52',
    Rent: '35K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '767',
    'Room No': '104',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1012',
    Type: '1BHK',
    Sector: 'Sector 52',
    Rent: '35K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '767',
    'Room No': '404',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1013',
    Type: '1BHK',
    Sector: 'Sector 52',
    Rent: '35K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '767',
    'Room No': '205',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1014',
    Type: '1BHK',
    Sector: 'Sector 52',
    Rent: '25K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': '675',
    'Room No': 'B002',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  },
  {
    PublicRef: 'MRH-1015',
    Type: '2BHK',
    Sector: 'Golf Course Road',
    Rent: '45K',
    ListingIntent: 'Rent',
    WebsiteStatus: 'Live',
    WebsiteDescription: '',
    'Property No': 'D2/8',
    'Room No': 'G001',
    Availability: 'Immediate',
    MediaFolderLink: '',
    PhotoFolder: '',
    Furnishing: '',
    Floor: '',
    Area: '',
    SocietyBuilding: '',
    Deposit: '',
    AvailableFrom: '',
    CarpetArea: ''
  }
];

function escapeCsvField(val: string): string {
  if (val.includes(',') || val.includes('"') || val.includes('\n')) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

function generateCSV() {
  const headers = [
    'PublicRef',
    'Type',
    'Sector',
    'Rent',
    'ListingIntent',
    'WebsiteStatus',
    'WebsiteDescription',
    'Property No',
    'Room No',
    'Availability',
    'MediaFolderLink',
    'PhotoFolder',
    'Furnishing',
    'Floor',
    'Area',
    'SocietyBuilding',
    'Deposit',
    'AvailableFrom',
    'CarpetArea'
  ];

  const lines = [headers.join(',')];
  for (const rec of records) {
    const row = headers.map(h => {
      const val = rec[h as keyof typeof rec] || '';
      return escapeCsvField(val);
    });
    lines.push(row.join(','));
  }

  const csvContent = lines.join('\n') + '\n';
  const outPath = path.join(__dirname, '..', 'data', 'crm-import.csv');
  fs.writeFileSync(outPath, csvContent, 'utf-8');
  console.log(`✓ Generated CRM CSV file: ${outPath}`);
}

generateCSV();
